module.exports = [
  {
    item_id: 0,
    title: "Blue Denim Jacket",
    price: 50,
    color: "blue",
    category: "trousers",
    style: "casual",
    material: "denim",
    item_img_url: "https://i.imgur.com/OYkyR5m.jpg",
  },
  {
    item_id: 1,
    title: "Cat Print Shirt",
    price: 20,
    color: "white",
    category: "shirts",
    style: "casual",
    material: "cotton",
    item_img_url: "https://i.imgur.com/rVbTPTD.jpg",
  },
  {
    item_id: 2,
    title: "Trendy Red Shoes",
    price: 60,
    color: "red",
    category: "shoes",
    style: "casual",
    material: "leather",
    item_img_url: "https://i.imgur.com/ksRACaQ.jpg",
  },
  {
    item_id: 3,
    title: "Grey Ripped Jeans",
    price: 35,
    color: "grey",
    category: "trousers",
    style: "casual",
    material: "denim",
    item_img_url: "https://i.imgur.com/IXovKq2.jpg",
  },
  {
    item_id: 4,
    title: "Brown Bomber Jacket",
    price: 45,
    color: "brown",
    category: "jackets",
    style: "casual",
    material: "cotton",
    item_img_url: "https://i.imgur.com/cuO6Oro.jpg",
  },
  {
    item_id: 5,
    title: "Red Running Shoes",
    price: 45,
    color: "red",
    category: "shoes",
    style: "athletic",
    material: "polyester",
    item_img_url: "https://i.imgur.com/GLsHdA5.jpg",
  },
  {
    item_id: 6,
    title: "Plain Black Shirt",
    price: 15,
    color: "black",
    category: "shirts",
    style: "casual",
    material: "cotton",
    item_img_url: "https://i.imgur.com/aTNKAJk.jpg",
  },
  {
    item_id: 7,
    title: "Blue Jeans",
    price: 25,
    color: "blue",
    category: "trousers",
    style: "casual",
    material: "denim",
    item_img_url: "https://i.imgur.com/i4Qv5ph.jpg",
  },
  {
    item_id: 8,
    title: "Red Corduroy Trousers",
    price: 65,
    color: "red",
    category: "trousers",
    style: "formal",
    material: "corduroy",
    item_img_url: "https://i.imgur.com/FcSD3v4.jpg",
  },
  {
    item_id: 9,
    title: "Brown Jumper",
    price: 85,
    color: "brown",
    category: "jackets",
    style: "casual",
    material: "wool",
    item_img_url: "https://i.imgur.com/RuSpGc9.jpg",
  },
  {
    item_id: 10,
    title: "Pink Trousers",
    price: 55,
    color: "pink",
    category: "trousers",
    style: "casual",
    material: "polyester",
    item_img_url: "https://i.imgur.com/1DOgt2z.jpg",
  },
  {
    item_id: 11,
    title: "Yellow Trainers",
    price: 40,
    color: "yellow",
    category: "shoes",
    style: "casual",
    material: "cotton",
    item_img_url: "https://i.imgur.com/ohymcno.jpg",
  },
  {
    item_id: 12,
    title: "Brown Jumper",
    price: 25,
    color: "brown",
    category: "jackets",
    style: "casual",
    material: "cotton",
    item_img_url: "https://i.imgur.com/sBovQxW.jpg",
  },
  {
    item_id: 13,
    title: "Brown Jersey Boots",
    price: 70,
    color: "brown",
    category: "shoes",
    style: "formal",
    material: "leather",
    item_img_url: "https://i.imgur.com/mu3SSZo.jpg",
  },
  {
    item_id: 14,
    title: "White Shirt",
    price: 25,
    color: "white",
    category: "shirts",
    style: "formal",
    material: "cotton",
    item_img_url: "https://i.imgur.com/A4DCgSz.jpg",
  },
  {
    item_id: 15,
    title: "Yellow Jorongo",
    price: 25,
    color: "yellow",
    category: "jackets",
    style: "casual",
    material: "cotton",
    item_img_url: "https://i.imgur.com/B6MVD56.jpg",
  },
  {
    item_id: 16,
    title: "Grey Backpack",
    price: 27,
    color: "grey",
    category: "misc",
    style: "formal",
    material: "cotton",
    item_img_url: "https://i.imgur.com/Y90e37R.jpg",
  },
  {
    item_id: 17,
    title: "Black Trousers",
    price: 32,
    color: "black",
    category: "trousers",
    style: "athletic",
    material: "polyester",
    item_img_url: "https://i.imgur.com/GV79zZc.jpg",
  },
  {
    item_id: 18,
    title: "Blue Jeans",
    price: 33.5,
    color: "blue",
    category: "trousers",
    style: "formal",
    material: "denim",
    item_img_url: "https://i.imgur.com/SE5QOG3.jpg",
  },
  {
    item_id: 19,
    title: "Coffee Print Shirt",
    price: 22.99,
    color: "white",
    category: "shirts",
    style: "casual",
    material: "cotton",
    item_img_url: "https://i.imgur.com/CEjJgMs.jpg",
  },
  {
    item_id: 20,
    title: "Black Running Shoes",
    price: 28.5,
    color: "black",
    category: "shoes",
    style: "athletic",
    material: "polyester",
    item_img_url: "https://i.imgur.com/bXT28qv.jpg",
  },
  {
    item_id: 21,
    title: "Chequered Corduroy Trousers",
    price: 55.99,
    color: "brown",
    category: "trousers",
    style: "formal",
    material: "corduroy",
    item_img_url: "https://i.imgur.com/kIgyY9S.jpg",
  },
  {
    item_id: 22,
    title: "Black Running Shoes",
    price: 44.99,
    color: "black",
    category: "shoes",
    style: "athletic",
    material: "polyester",
    item_img_url: "https://i.imgur.com/dIAfL4S.jpg",
  },
  {
    item_id: 23,
    title: "Pink Trainers",
    price: 29.99,
    color: "pink",
    category: "shoes",
    style: "athletic",
    material: "polyester",
    item_img_url: "https://i.imgur.com/NuR7zg7.jpg",
  },
  {
    item_id: 24,
    title: "High Top Trainers",
    price: 85,
    color: "white",
    category: "shoes",
    style: "casual",
    material: "leather",
    item_img_url: "https://i.imgur.com/ppduyEj.jpg",
  },
  {
    item_id: 25,
    title: "Grey Running Trainers",
    price: 57.99,
    color: "grey",
    category: "shoes",
    style: "athletic",
    material: "polyester",
    item_img_url: "https://i.imgur.com/L3uqxLm.jpg",
  },
  {
    item_id: 26,
    title: "Denim Jacket",
    price: 44.99,
    color: "blue",
    category: "jackets",
    style: "casual",
    material: "denim",
    item_img_url: "https://i.imgur.com/HvyOmsV.jpg",
  },
  {
    item_id: 27,
    title: "Blue T-Shirt",
    price: 15.5,
    color: "blue",
    category: "shirts",
    style: "casual",
    material: "cotton",
    item_img_url: "https://i.imgur.com/hopkdn8.jpg",
  },
  {
    item_id: 28,
    title: "Sporty Black Trainers",
    price: 29.99,
    color: "black",
    category: "shoes",
    style: "athletic",
    material: "polyester",
    item_img_url: "https://i.imgur.com/BjV1h3x.jpg",
  },
  {
    item_id: 29,
    title: "Grey Running Shoes",
    price: 37.99,
    color: "grey",
    category: "shoes",
    style: "athletic",
    material: "polyester",
    item_img_url: "https://i.imgur.com/dsIdX3O.jpg",
  },
  {
    item_id: 30,
    title: "Grey Jacket",
    price: 37.49,
    color: "grey",
    category: "jackets",
    style: "casual",
    material: "cotton",
    item_img_url: "https://i.imgur.com/lFzqmFy.jpg",
  },
  {
    item_id: 31,
    title: "White Male Trainers With Black",
    price: 87.49,
    color: "white",
    category: "shoes",
    style: "casual",
    material: "leather",
    item_img_url: "https://i.imgur.com/QHFchHR.jpg",
  },
  {
    item_id: 32,
    title: "Smart Red Shirt",
    price: 29.99,
    color: "red",
    category: "shirts",
    style: "formal",
    material: "cotton",
    item_img_url: "https://i.imgur.com/GTOkB5q.jpg",
  },
  {
    item_id: 33,
    title: "White Wooly Jumper",
    price: 45.5,
    color: "white",
    category: "jumpers",
    style: "casual",
    material: "wool",
    item_img_url: "https://i.imgur.com/sne40XE.jpg",
  },
  {
    item_id: 34,
    title: "White Trainers",
    price: 77.79,
    color: "white",
    category: "shoes",
    style: "casual",
    material: "leather",
    item_img_url: "https://i.imgur.com/sFG4y0i.jpg",
  },
  {
    item_id: 35,
    title: "Black Print Shirt",
    price: 19.99,
    color: "black",
    category: "shirts",
    style: "casual",
    material: "cotton",
    item_img_url: "https://i.imgur.com/fAhoyKQ.jpg",
  },
  {
    item_id: 36,
    title: "White Running Trainers",
    price: 29.99,
    color: "white",
    category: "shoes",
    style: "athletic",
    material: "polyester",
    item_img_url: "https://i.imgur.com/kvK1Pu7.jpg",
  },
  {
    item_id: 37,
    title: "Light Fade Jeans",
    price: 39.5,
    color: "blue",
    category: "trousers",
    style: "casual",
    material: "denim",
    item_img_url: "https://i.imgur.com/2vhTYC8.jpg",
  },
  {
    item_id: 38,
    title: "Blue Running Trainers",
    price: 39.5,
    color: "blue",
    category: "shoes",
    style: "athletic",
    material: "polyester",
    item_img_url: "https://i.imgur.com/FKLMDLv.jpg",
  },
  {
    item_id: 39,
    title: "Casual Blue Shirt",
    price: 14.99,
    color: "blue",
    category: "shirts",
    style: "casual",
    material: "cotton",
    item_img_url: "https://i.imgur.com/itoTD9C.jpg",
  },
  {
    item_id: 40,
    title: "Smart White Shirt",
    price: 24.5,
    color: "white",
    category: "shirts",
    style: "formal",
    material: "cotton",
    item_img_url: "https://i.imgur.com/1erDwok.jpg",
  },
  {
    item_id: 41,
    title: "Casual Black Trainers",
    price: 32.5,
    color: "black",
    category: "shoes",
    style: "casual",
    material: "cotton",
    item_img_url: "https://i.imgur.com/vL36QwU.jpg",
  },
  {
    item_id: 42,
    title: "Trendy Blue Shirt",
    price: 89.99,
    color: "blue",
    category: "shirts",
    style: "casual",
    material: "cotton",
    item_img_url: "https://i.imgur.com/hArOoi0.jpg",
  },
  {
    item_id: 43,
    title: "Black Gilet",
    price: 45.5,
    color: "black",
    category: "jackets",
    style: "athletic",
    material: "polyester",
    item_img_url: "https://i.imgur.com/5HZ4Q03.jpg",
  },
  {
    item_id: 44,
    title: "Orange Trainers",
    price: 32.5,
    color: "orange",
    category: "shoes",
    style: "casual",
    material: "cotton",
    item_img_url: "https://i.imgur.com/inUovkS.jpg",
  },
];
