module.exports = [
  {
    item_id: 0,
    title: "Blue Denim Jacket",
    price: 50,
    color: "blue",
    style: "casual",
    material: "denim",
    item_img_url: "https://i.imgur.com/OYkyR5m.jpg",
  },
  {
    item_id: 1,
    title: "Cat Print Shirt",
    price: 20,
    color: "white",
    style: "casual",
    material: "cotton",
    item_img_url: "https://i.imgur.com/rVbTPTD.jpg",
  },
  {
    item_id: 2,
    title: "Trendy Red Shoes",
    price: 60,
    color: "red",
    style: "casual",
    material: "leather",
    item_img_url: "https://i.imgur.com/ksRACaQ.jpg",
  },
  {
    item_id: 3,
    title: "Grey Ripped Jeans",
    price: 35,
    color: "grey",
    style: "casual",
    material: "denim",
    item_img_url: "https://i.imgur.com/IXovKq2.jpg",
  },
  {
    item_id: 4,
    title: "Brown Bomber Jacket",
    price: 45,
    color: "brown",
    style: "casual",
    material: "cotton",
    item_img_url: "https://i.imgur.com/cuO6Oro.jpg",
  },
  {
    item_id: 5,
    title: "Red Running Shoes",
    price: 45,
    color: "red",
    style: "athletic",
    material: "polyester",
    item_img_url: "https://i.imgur.com/GLsHdA5.jpg",
  },
  {
    item_id: 6,
    title: "Plain Black Shirt",
    price: 15,
    color: "black",
    style: "casual",
    material: "cotton",
    item_img_url: "https://i.imgur.com/aTNKAJk.jpg",
  },
  {
    item_id: 7,
    title: "Blue Jeans",
    price: 25,
    color: "blue",
    style: "casual",
    material: "denim",
    item_img_url: "https://i.imgur.com/i4Qv5ph.jpg",
  },
  {
    item_id: 8,
    title: "Red Corduroy Trousers",
    price: 65,
    color: "red",
    style: "formal",
    material: "corduroy",
    item_img_url: "https://i.imgur.com/FcSD3v4.jpg",
  },
  {
    item_id: 9,
    title: "Brown Jumper",
    price: 85,
    color: "brown",
    style: "casual",
    material: "wool",
    item_img_url: "https://i.imgur.com/RuSpGc9.jpg",
  },
  {
    item_id: 10,
    title: "Pink Trousers",
    price: 55,
    color: "pink",
    style: "casual",
    material: "polyester",
    item_img_url: "https://i.imgur.com/1DOgt2z.jpg",
  },
  {
    item_id: 11,
    title: "Yellow Trainers",
    price: 40,
    color: "yellow",
    style: "casual",
    material: "cotton",
    item_img_url: "https://i.imgur.com/ohymcno.jpg",
  },
  {
    item_id: 12,
    title: "Brown Jumper",
    price: 25,
    color: "brown",
    style: "casual",
    material: "cotton",
    item_img_url: "https://i.imgur.com/sBovQxW.jpg",
  },
  {
    item_id: 13,
    title: "Brown Jersey Boots",
    price: 70,
    color: "brown",
    style: "formal",
    material: "leather",
    item_img_url: "https://i.imgur.com/mu3SSZo.jpg",
  },
  {
    item_id: 14,
    title: "White Shirt",
    price: 25,
    color: "white",
    style: "formal",
    material: "cotton",
    item_img_url: "https://i.imgur.com/A4DCgSz.jpg",
  },
  {
    item_id: 15,
    title: "Yellow Jorongo",
    price: 25,
    color: "yellow",
    style: "casual",
    material: "cotton",
    item_img_url: "https://i.imgur.com/B6MVD56.jpg",
  },
  {
    item_id: 16,
    title: "Grey Backpack",
    price: 27,
    color: "grey",
    style: "formal",
    material: "cotton",
    item_img_url: "https://i.imgur.com/Y90e37R.jpg",
  },
  {
    item_id: 17,
    title: "Black Trousers",
    price: 32,
    color: "black",
    style: "athletic",
    material: "polyester",
    item_img_url: "https://i.imgur.com/GV79zZc.jpg",
  },
  {
    item_id: 18,
    title: "Blue Jeans",
    price: 33.5,
    color: "blue",
    style: "formal",
    material: "denim",
    item_img_url: "https://i.imgur.com/SE5QOG3.jpg",
  },
  {
    item_id: 19,
    title: "Coffee Print Shirt",
    price: 22.99,
    color: "white",
    style: "casual",
    material: "cotton",
    item_img_url: "https://i.imgur.com/CEjJgMs.jpg",
  },
  {
    item_id: 20,
    title: "Black Running Shoes",
    price: 28.5,
    color: "black",
    style: "athletic",
    material: "polyester",
    item_img_url: "https://i.imgur.com/bXT28qv.jpg",
  },
  {
    item_id: 21,
    title: "Chequered Corduroy Trousers",
    price: 55.99,
    color: "brown",
    style: "formal",
    material: "corduroy",
    item_img_url: "https://i.imgur.com/kIgyY9S.jpg",
  },
  {
    item_id: 22,
    title: "Black Running Shoes",
    price: 44.99,
    color: "black",
    style: "athletic",
    material: "polyester",
    item_img_url: "https://i.imgur.com/dIAfL4S.jpg",
  },
  {
    item_id: 23,
    title: "Pink Trainers",
    price: 29.99,
    color: "pink",
    style: "athletic",
    material: "polyester",
    item_img_url: "https://i.imgur.com/NuR7zg7.jpg",
  },
  {
    item_id: 24,
    title: "High Top Trainers",
    price: 85,
    color: "white",
    style: "casual",
    material: "leather",
    item_img_url: "https://i.imgur.com/ppduyEj.jpg",
  },
  {
    item_id: 25,
    title: "Grey Running Trainers",
    price: 57.99,
    color: "grey",
    style: "athletic",
    material: "polyester",
    item_img_url: "https://i.imgur.com/L3uqxLm.jpg",
  },
  {
    item_id: 26,
    title: "Denim Jacket",
    price: 44.99,
    color: "blue",
    style: "casual",
    material: "denim",
    item_img_url: "https://i.imgur.com/HvyOmsV.jpg",
  },
  {
    item_id: 27,
    title: "Blue T-Shirt",
    price: 15.5,
    color: "blue",
    style: "casual",
    material: "cotton",
    item_img_url: "https://i.imgur.com/hopkdn8.jpg",
  },
  {
    item_id: 28,
    title: "Sporty Black Trainers",
    price: 29.99,
    color: "black",
    style: "athletic",
    material: "polyester",
    item_img_url: "https://i.imgur.com/BjV1h3x.jpg",
  },
  {
    item_id: 29,
    title: "Grey Running Shoes",
    price: 37.99,
    color: "grey",
    style: "athletic",
    material: "polyester",
    item_img_url: "https://i.imgur.com/dsIdX3O.jpg",
  },
];